version: '3.2'
networks:
  cluster_net:
#    external:
#      name: cassandra-net
services:
  funnel:
    build: .
    stdin_open: true
    environment:
        cassandra.keyspace: siesta
        cassandra.max_requests_per_local_connection: 32768
        cassandra.max_requests_per_remote_connection: 22000
        cassandra.connections_per_host: 1000
        cassandra.max_queue_size: 1024
        cassandra.connection_timeout: 30000
        cassandra.read_timeout: 30000
        cassandra.contactpoints: 
        cassandra.port: 
        cassandra.user: 
        cassandra.password: 
        server.port: 8080
    volumes:
      - ./build:/root/.m2
    ports:
      - '8080:8080'
    networks:
      - cluster_net
