version: '2'
services:
  funnel:
    build: .
    stdin_open: true
    environment:
        cassandra.keyspace: sequenceetection
        cassandra.max_requests_per_local_connection: 32768
        cassandra.max_requests_per_remote_connection: 22000
        cassandra.connections_per_host: 1000
        cassandra.max_queue_size: 1024
        cassandra.connection_timeout: 30000
        cassandra.read_timeout: 30000
        cassandra.contactpoints: "rabbit.csd.auth.gr"
        cassandra.port: "9042"
        cassandra.user: "cassandra"
        cassandra.password: "cassandra"
        server.port: 8080
    volumes:
      - ./build:/root/.m2
    ports:
      - '8080:8080'